version: '3.8'
services:
  db:
    image: postgres:17
    container_name: player-hub-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres005
      POSTGRES_DB: player-hub
    ports:
      - "5433:5433"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data 